services:
  postgres:
    image: postgres:17.3
    container_name: lazy_ledger_postgres
    environment:
      POSTGRES_DB: lazy_ledger_db
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lazy_ledger_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: lazy_ledger_app
    ports:
      - "8090:8090"
    volumes:
      # Monta tu c√≥digo fuente local en el directorio de trabajo del contenedor
      - ./src:/app/src
      - ~/.m2:/root/.m2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lazy_ledger_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-DuqmFuAE9rkpu5Ot4NCULGjIjZ50kC//pX5xVuIeZBWiyT5H3YM6P/bXuA9y8lJV+ikmTEe+TZrJMa92u+ArOw==}
    networks:
      - lazy_ledger_network


volumes:
  postgres_data:

networks:
  lazy_ledger_network: